wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701202113.666539
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
data_dir:
  desc: null
  value: /Users/jacob/Documents/albert_pytorch/scripts/../dataset/sst-2/
model_type:
  desc: null
  value: albert
model_name_or_path:
  desc: null
  value: /Users/jacob/Documents/albert_pytorch/scripts/../prev_trained_model/albert_base_v2
task_name:
  desc: null
  value: sst-2
output_dir:
  desc: null
  value: /Users/jacob/Documents/albert_pytorch/scripts/../outputs/sst-2_output/albert
vocab_file:
  desc: null
  value: ''
spm_model_file:
  desc: null
  value: /Users/jacob/Documents/albert_pytorch/scripts/../prev_trained_model/albert_base_v2/30k-clean.model
config_name:
  desc: null
  value: ''
tokenizer_name:
  desc: null
  value: ''
cache_dir:
  desc: null
  value: ''
max_seq_length:
  desc: null
  value: 128
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_lower_case:
  desc: null
  value: true
per_gpu_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: 8
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_epsilon:
  desc: null
  value: 1.0e-06
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: -1
warmup_proportion:
  desc: null
  value: 0.1
logging_steps:
  desc: null
  value: 4210
save_steps:
  desc: null
  value: 4210
eval_all_checkpoints:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: true
overwrite_cache:
  desc: null
  value: false
seed:
  desc: null
  value: 42
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
local_rank:
  desc: null
  value: -1
server_ip:
  desc: null
  value: ''
server_port:
  desc: null
  value: ''
n_gpu:
  desc: null
  value: 0
device:
  desc: null
  value: mps
output_mode:
  desc: null
  value: classification
train_batch_size:
  desc: null
  value: 16
warmup_steps:
  desc: null
  value: 1263
